# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
#  pod 'Alamofire', '~> 5.3'
#  pod 'Kingfisher', '~> 6.3.1'
  pod 'SnapKit', '~> 5.6.0'
  pod 'HandyJSON', '~> 5.0.2'

end
